[package]
name = "webgpu_compute"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1"
log = "0.4.22"
parking_lot = "0.12"
thiserror = "1"
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread", "time"] }
wgpu = "22"
